### ISSUE TITLE
Runnin edax-reversi on mac

### ISSUE THREAD

**Issue by ishanSrt** [abulmo/edax-reversi#11]
There is no 7zip file for mac in Assets in the GitHub releases page.
I tried running the linux executable, which gave me an `exec format error`
On trying to build from the source, I did `make release OS=osx COMP=clang ARCH=x64`, *(I have a 2016 macbook pro 13 inch without touchbar)*
which gave me this log:
https://gist.github.com/ishanSrt/db03df64298e09b80a9d96a088174587 
Can you help me out with this?

**Comment by abulmo** [comment]
try _make pgo-build OS=osx COMP=clang_
_make release_ was for me to compile for all platform from linux (unfortunately, the cross-compiler for apple osx is no more availabe in my linux distro).

**Comment by ishanSrt** [comment]
Hi! thanks for replying. I had already tried that earlier. Here's the log
```
building edax with pgo...
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make clean
rm -f pgopti* *.dyn all.gc* *~ *.o generate_flip generate_count_flip *.prof*
clang -std=c99 -pedantic -W -Wall -D_GNU_SOURCE=1 -Wno-invalid-source-encoding -O3 -flto -ffast-math -fomit-frame-pointer -DNDEBUG -fuse-ld=gold -m64 -march=native -DUSE_GAS_X64 -DPOPCOUNT -mmacosx-version-min=10.4 -mdynamic-no-pic -DHAS_CPU_64 -fprofile-instr-generate all.c -o ../bin/mEdax -lm -lpthread
clang: error: invalid linker name in argument '-fuse-ld=gold'
make: *** [pgo-build] Error 1
```

**Comment by henry-p** [comment]
@ishanSrt I got it to work on a MBP 2018:
Install GCC compiler (I use Homebrew): `brew install gcc`
`cd ~/edax-reversi/src`
`mkdir ../bin` (this is important!)
Unzip eval.7z to `~/edax-reversi/bin` (such that `~/edax-reversi/bin/data/eval.dat` exists`
`make build ARCH=x64-modern COMP=gcc OS=osx`
Now you should see `~/edax-reversi/bin/mEdax`
You might need to do `chmod +x ~/edax-reversi/bin/mEdax` in order to be able to run it standalone.

**Comment by henry-p** [comment]
Adding to the previous comment:
In order to get the `pgo-build` to work, you need to make sure there's no `mEdax` in `~/edax-reversi/bin`, and you need to move the `problem` folder from `~/edax-reversi` to `~/edax-reversi/bin`.

**Comment by henry-p** [comment]
@abulmo This is probably not high on your priorities list, but in order to get rid of the `clang: error: invalid linker name in argument '-fuse-ld=gold'`, I suggest switching to the LLVM linker. Reasoning can be found here: https://bcain-llvm.readthedocs.io/projects/lld/en/latest/

**Comment by abulmo** [comment]
I project to install OS X on a virtual box, so that I can provide and test binaries by myself and follow the evolution of the OS, compilers and other tools. The gold linker is indeed only available under Linux, and should not have been seen on the Mac compile. The lld linker might be a good replacement, but it is a "recent" addition to the llvm suite, at least compared to Edax age, so I did not used it at the time I produce Edax binaries. 
Be patient as Edax is low now in my priorities, and I have too little time to spend on it.

**Comment by sensuikan1973** [comment]
We can build edax on Mac,Windows,Linux with [GitHub virtual machine](https://docs.github.com/ja/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners).

If we create the job, anyone can obtain every executable assets.
Actually, I did. -> e.g. https://github.com/sensuikan1973/edax_runner/blob/main/.github/workflows/publish_artifacts.yaml

If you agree this plan, I will create PullRequest.

**Comment by abulmo** [comment]
I finally compiled the version 4.4 for Mac OS X after installing a virtual machine on my computer. For maximum compatibility I targeted the old nehalem CPU (which supports popcount instruction) and Mac-OS X 10.10 64 bits or later.
