### ISSUE TITLE
Could the tool which is used to generate the eval.dat be available?

### ISSUE THREAD

**Issue by zhu-jz** [abulmo/edax-reversi#4]
And it would be great to know the details about how to generate the evaluation data, thanks!

**Comment by zhu-jz** [comment]
oh, i see, there is a file eval_builder.c

**Comment by abulmo** [comment]
The presence of the eval_builder.c file is  more for information purpose than for usage. This program presents a set of tools rather than a simple ready-to-use evaluation weight provider. To build an eval.dat file you need a big set of games (I used around 800,000 games), both various in the opening and of high quality in the endgame. I built the current evaluation weights in 2002. I first used an optimizer (with conjugate gradient, but I do not remember which one) to minimize the absolute error between the evaluation and the game outcome. I then filter the weights both spatially and temporally to smooth the weights and to fill-in the missing patterns. This process was retried 2 or 3 times. I also controlled the results by performing fast games at depth 1 to control the quality of the resulting weights.
